Developmental
magoed12/CMP1903_A1_2324_fork pull request #1
Opened 2024-03-04 21:18 UTC by magoed12

2024-03-04 21:26 UTC, rapidslayer101 approved these changes
Good development of code can be seen, there seems to be room to be more consistent with implicitly typed and explicitly typed variables. Good use of comments to describe code which helps the code be more readable. The code meets the brief requirements. Error checking can be seen in the test class.

2024-03-05 19:44 UTC, JoshyTM123 commented on CMP1903_A1_2324/Game.cs
> +        }
Good commenting, code makes sense and follows the c# style sheet

2024-03-05 19:44 UTC, JoshyTM123 commented on CMP1903_A1_2324/Die.cs
> +        }
Commenting was done nicely and code follows c# style structure

2024-03-05 19:49 UTC, JoshyTM123 requested changes
In the program class, you have not created a game object and called it's methods. This should probably be added, but other than that you've used good commenting, your code follows the c# coding style, your code is fairly easy to read, and in the test class you've used a good amount of error handling.

2024-03-05 19:49 UTC, JoshyTM123 commented on CMP1903_A1_2324/Testing.cs
> +        }
Code follows coding style correctly, comments used well

2024-03-05 19:49 UTC, JoshyTM123 commented on CMP1903_A1_2324/Program.cs
>          }
You are missing the 'create a game object and call its methods' part out here!

2024-03-06 19:19 UTC, merged